Get system from pkgs.stdenv.hostPlatform...
...instead of config.nixpkgs.

error: Neither nixpkgs.system nor any other option in nixpkgs.* is meant
to be read by modules and configurations.
Use pkgs.stdenv.hostPlatform instead.